module.exports = [
    [1, {question: 'Quels objets dois-tu trouver pour remplir ta collection ?', answers: ["CARTE", "CARTES"], url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1655889411/gon_freecss_12702_tfp0om.jpg", id: 1, name: 'Gon', description: "Le héros de Chasseur x Chasseur", rarity: "Commune"}],
    [2, {question: 'Dans Hunter x Hunter, combien de cartes faut-il collectionner pour finir le jeu Greed Island ?', answers: ["100", "CENT"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1655932601/Killua-2011_zkb8ki.webp", id: 2, name: 'Kirua', description: "Personnage de HxH", rarity: "Commune"}],
    [3, {question: 'Dans Jujutsu Kaisen, combien y a-t-il de reliques des doigts de Sukuna ?', answers: ["20", "VINGT"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1655929269/Yuji_Itadori_Volume_1_zlexuq.webp", id: 3, name: 'Yuji', description: " Personnage de JJK", rarity: "Commune"}],
    [4, {question: 'Quel studio adapte Jujutsu Kaisen ?', answers: ["MAPPA"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1655920831/Satoru_Gojo_Manga_o7ckbf.webp", id: 4, name: 'Gojo', description: "Personnage de JJK", rarity: "Épique"}],
    [5, {question: 'Dans MHA, à quel personnage de BD française ressemble Mirio Togata ?', answers: ["TINTIN"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1655931420/Mirio_Costume_hep0fa.webp", id: 5, name: 'Mirio', description: "Personnage de MHA", rarity: "Rare"}],
    [6, {question: 'Qui devient le héros n°1 après All Might dans My Hero Academia ?', answers: ["ENDEAVOR"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1655932775/Todoroki_Infobox_iiryic.webp", id: 6, name: 'Todoroki', description: "Personnage de MHA", rarity: "Commune"}],
    [7, {question: 'Quel est le nom de la petite fille dans Spy x Family', answers: ["ANYA"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1655930233/Anya_Forger_Anime_orrgyk.webp", id: 7, name: 'Anya', description: "Personnage de SxF", rarity: "Rare"}],
    [8, {question: 'Quel est le nom de code de Loid Forger dans Spy x Family ?', answers: ["TWILIGHT"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1655929519/Loid_Forger_Colored_Full_Body_x1oqa6.webp", id: 8, name: 'Twilight', description: "Personnage de SxF", rarity: "Commune"}],
    [9, {question: 'Combien y a-t-il de Titans Primordiaux dans L\'Attaque des Titans ?', answers: ["9", "NEUF"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1655927651/Eren-Yeager-PNG-Image_nleieg.png", id: 9, name: 'Eren', description: "Personnage de SNK", rarity: "Rare"}],
    [10, {question: 'Quel animateur japonais est célèbre pour avoir animé les scènes d\'action de Levi dans L\'Attaque des Titans ?', answers: ["IMAIARIFUMI", "ARIFUMIIMAI"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1655921231/Captain-Levi-Ackerman-PNG-Transparent-Image_xbros8.png", id: 10, name: 'Levi', description: "Personnage de SNK", rarity: "Épique"}],

    [11, {question: 'Dans One Piece, comment s\'appellent les fruits du démon qui permettent à son utilisateur de prendre la forme d\'un élément naturel ?', answers: ["LOGIA"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656358593/11-20/q7LDgDk_e8juay.png", id: 11, name: 'Law', description: "Personnage de OP", rarity: "Commune"}],
    [12, {question: 'Quel est le nom de l\'île natale de Luffy, le personnage de One Piece ?', answers: ["DAWN"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656358687/11-20/Luffy-PNG-Photos_xqt30h.png", id: 12, name: 'Luffy', description: "Personnage de OP", rarity: "Commune"}],
    [13, {question: 'Comment s\'appelle le jeu pierre-feuille-ciseaux au Japon ?', answers: ["JANKENPON"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656355748/11-20/Ryuko-Matoi-PNG-HD_gsh0oz.png", id: 13, name: 'Ryuko', description: "Personnage de KLK", rarity: "Rare"}],
    [14, {question: 'Quel est le nom de l\'art du découpage du papier dans la culture japonaise ?', answers: ["KIRIGAMI"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656356118/11-20/c0a6fda4ac637c8c61d9ee568ab6e1c3_sebnim.png", id: 14, name: 'Mako', description: "Personnage de KLK", rarity: "Rare"}],
    [15, {question: 'Quel est le plat traditionel de Noël au Japon ?', answers: ["KFC"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656356422/11-20/a5ed2270b64d13210ba34b4233d3aa78_gsguh3.jpg", id: 15, name: 'Itachi et sa poule', description: "Itachi et sa poule", rarity: "Épique"}],
    [16, {question: 'Quel artiste japonais a peint ce tableau ? ("La Grande Vague de Kanagawa")', answers: ["HOKUSAI", "KATSUSHIKAHOKUSAI", "HOKUSAIKATSUSHIKA"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656356590/11-20/image_2022-05-12_031619872-819x1024_fyexkf.png", id: 16, name: 'Yaguchi', description: "Personnage de Blue Period", rarity: "Rare"}],
    [17, {question: 'Comment s\'appelle le mouvement artistique japonais qui consiste à graver des estampes sur du bois ?', answers: ["UKIYO-E", "UKIYOE", "UKIYO"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656357981/11-20/Kuwana.Maki.full.3611735_kyyqya.png", id: 17, name: 'Maki', description: "Personnage de Blue Period", rarity: "Épique"}],
    [18, {question: 'En quelle année est sortie le premier film du studio Ghibli ?', answers: ["1986"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656358343/11-20/My-Neighbor-Totoro-Transparent-Background_cmuxlw.png", id: 18, name: 'Totoro', description: "Personnage du Studio Ghibli", rarity: "Commune"}],
    [19, {question: 'Comment s\'appelle la décoration culinaire japonaise à base de poisson et avec une spirale rose ?', answers: ["NARUTOMAKI"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656355303/11-20/Naruto-Shippuden-PNG-Free-Download_nkljj7.png", id: 19, name: 'Naruto', description: "Personnage de Naruto", rarity: "Commune"}],
    [20, {question: 'Comment dit on "cerisier" en japonais ?', answers: ["SAKURA"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656355647/11-20/73-732685_sakura-4-naruto-shippuden-sakura-png_kniumq.png", id: 20, name: 'Sakura', description: "Personnage de Naruto", rarity: "Commune"}],

    [21, {question: 'Who\'s that Pokemon ?', answers: ["MIMIQUI","MIMIKYU"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656369481/21-30/1200px-Mimiqui__Forme_D%C3%A9guis%C3%A9e_-SL_pakx0h.png", id: 21, name: 'Mimiqui', description: "Pokemon", rarity: "Épique"}],
    [22, {question: 'Who\'s that Pokemon ?', answers: ["GERMIGNON","CHIKORITA"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656369481/21-30/Germignon-HGSS_v5xtdw.png", id: 22, name: 'Germignon', description: "Pokemon", rarity: "Commune"}],
    [23, {question: 'Who\'s that Pokemon ?', answers: ["FOUINAR","FURRET"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656369482/21-30/1200px-Fouinar-HGSS_rqhga2.png", id: 23, name: 'Fouinar', description: "Pokemon", rarity: "Rare"}],
    [24, {question: 'Who\'s that Pokemon ?', answers: ["SALAMÈCHE","SALAMECHE","CHARMANDER"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656369481/21-30/Salam%C3%A8che-RFVF_djpunz.png", id: 24, name: 'Salamèche', description: "Pokemon", rarity: "Commune"}],
    [25, {question: 'Qui est ce personnage ?', answers: ["EDWARD","EDWARDELRIC","ELRICEDWARD"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656454933/21-30/NicePng_edward-elric-png_1698428_dr9ufn.png", id: 25, name: 'Edward', description: "Personnage de FMAB", rarity: "Commune"}],
    [26, {question: 'Qui est ce personnage ?', answers: ["SENKU","SENKUISHIGAMI","ISHIGAMISENKU"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656454933/21-30/Senku_Ishigami_Anime_corbhg.webp", id: 26, name: 'Senku', description: "Personnage de Dr.Stone", rarity: "Rare"}],
    [27, {question: 'Qui est ce personnage ?', answers: ["L"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656454933/21-30/Death_Note_L_v342wu.webp", id: 27, name: 'L', description: "Personnage de Death Note", rarity: "Commune"}],
    [28, {question: 'Qui est ce personnage ?', answers: ["MEGUMIN"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656454933/21-30/toppng.com-megumin-5pb-kono-subarashii-sekai-ni-shukufuku-wo-kono-yokubukai-799x990_jkp9o2.png", id: 28, name: 'Megumin', description: "Personnage de Konosuba", rarity: "Rare"}],
    [29, {question: 'Qui est ce personnage ?', answers: ["KYOJURORENGOKU","RENGOKUKYOJURO","RENGOKU","KYOJURO"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656454933/21-30/Rengoku_Profile_hgrgmw.webp", id: 29, name: 'Rengoku', description: "Personnage de Demon Slayer", rarity: "Épique"}],
    [30, {question: 'Qui est ce personnage ?', answers: ["HINATA","SHOYOHINATA","HINATASHOYO"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656454933/21-30/dlf.pt-hinata-png-4615651_bilmfp.png", id: 30, name: 'Hinata', description: "Personnage de Haikyuu", rarity: "Commune"}],

    [31, {question: 'Décodez ce message :', answers: ["VOEUX"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656456853/31-40/Emma_Anime_ctwqb1.webp", id: 31, name: 'Emma', description: "Personnage de Promised Neverland", rarity: "Épique"}],
    [32, {question: 'Décodez ce message :', answers: ["JAMAIS"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656456853/31-40/Norman_Anime_r2z2dw.webp", id: 32, name: 'Norman', description: "Personnage de Promised Neverland", rarity: "Commune"}],
    [33, {question: 'Décodez ce message :', answers: ["TERRE"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656456854/31-40/ray-1_zh1khr.png", id: 33, name: 'Ray', description: "Personnage de Promised Neverland", rarity: "Commune"}],
    [34, {question: 'Décodez ce code césar de 5 :', answers: ["LUNE"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656514685/31-40/Capture_mprldh.png", id: 34, name: 'Kaguya', description: "Personnage de Kaguya Sama: Love is war", rarity: "Commune"}],
    [35, {question: 'Décodez ce code césar de 5 :', answers: ["ARGENT"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656514740/31-40/shirogane_miyuki_17945_vydkmj.jpg", id: 35, name: 'Shirogane', description: "Personnage de Kaguya Sama: Love is war", rarity: "Commune"}],
    [36, {question: 'Décodez ce code césar de 5 :', answers: ["POULET"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656514782/31-40/EvkxJWwXIAEbbZb_v64h0s.jpg", id: 36, name: 'Fujiwara', description: "Personnage de Kaguya Sama: Love is war", rarity: "Rare"}],
    [37, {question: 'Décodez ce message :', answers: ["LETTRE"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656515544/31-40/conan_fg3b2w.png", id: 37, name: 'Conan', description: "Personnage de Detective Conan", rarity: "Commune"}],
    [38, {question: 'Décodez ce message :', answers: ["VOYAGE"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656516726/31-40/Hinazuki.Kayo.full.1977538_s7iykd.jpg", id: 38, name: 'Kayo', description: "Personnage de Erased", rarity: "Rare"}],
    [39, {question: 'Décodez ce message :', answers: ["INDICE"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656517109/31-40/b4aceb004b1e02534a924b393260fad4ab57fd65v2_00_alq3z7.jpg", id: 39, name: 'Kaori', description: "Personnage de Your Lie in April", rarity: "Épique"}],
    [40, {question: 'Décodez ce message :', answers: ["PIANO"],  url: "https://res.cloudinary.com/dbhr3yfi5/image/upload/v1656517674/31-40/Kosei_Arima_Infobox_wmipbz.webp", id: 40, name: 'Kosei', description: "Personnage de Your Lie in April", rarity: "Commune"}],
    
    [41, {question: '', answers: [""],  url: "", id: 41, name: '', description: "Personnage de", rarity: ""}],
]   

// 50 énigmes
// Catégories : culture anime/manga, culture jap, pokemon, énigmes "réelles", anim 
//      10 énigmes de chaque catégorie
// 1 Intro
// 2-10 Culture Manga
// 11-20 Culture Jap
// 21-30 Silhouettes

// 31-40 Culture Enigmes (lettre miroir x3, code césar x3 ) 9
// 41-50 Anim (tournoi ninja, cache cache, PFC ++, morpion ++)